// Automatically generated by MockGen. DO NOT EDIT!
// Source: vendor/github.com/aws/aws-sdk-go/service/sns/snsiface/interface.go

package mocks

import (
	request "github.com/aws/aws-sdk-go/aws/request"
	sns "github.com/aws/aws-sdk-go/service/sns"
	gomock "github.com/golang/mock/gomock"
)

// Mock of SNSAPI interface
type MockSNSAPI struct {
	ctrl     *gomock.Controller
	recorder *_MockSNSAPIRecorder
}

// Recorder for MockSNSAPI (not exported)
type _MockSNSAPIRecorder struct {
	mock *MockSNSAPI
}

func NewMockSNSAPI(ctrl *gomock.Controller) *MockSNSAPI {
	mock := &MockSNSAPI{ctrl: ctrl}
	mock.recorder = &_MockSNSAPIRecorder{mock}
	return mock
}

func (_m *MockSNSAPI) EXPECT() *_MockSNSAPIRecorder {
	return _m.recorder
}

func (_m *MockSNSAPI) AddPermissionRequest(_param0 *sns.AddPermissionInput) (*request.Request, *sns.AddPermissionOutput) {
	ret := _m.ctrl.Call(_m, "AddPermissionRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.AddPermissionOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) AddPermissionRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddPermissionRequest", arg0)
}

func (_m *MockSNSAPI) AddPermission(_param0 *sns.AddPermissionInput) (*sns.AddPermissionOutput, error) {
	ret := _m.ctrl.Call(_m, "AddPermission", _param0)
	ret0, _ := ret[0].(*sns.AddPermissionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) AddPermission(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddPermission", arg0)
}

func (_m *MockSNSAPI) CheckIfPhoneNumberIsOptedOutRequest(_param0 *sns.CheckIfPhoneNumberIsOptedOutInput) (*request.Request, *sns.CheckIfPhoneNumberIsOptedOutOutput) {
	ret := _m.ctrl.Call(_m, "CheckIfPhoneNumberIsOptedOutRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.CheckIfPhoneNumberIsOptedOutOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) CheckIfPhoneNumberIsOptedOutRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CheckIfPhoneNumberIsOptedOutRequest", arg0)
}

func (_m *MockSNSAPI) CheckIfPhoneNumberIsOptedOut(_param0 *sns.CheckIfPhoneNumberIsOptedOutInput) (*sns.CheckIfPhoneNumberIsOptedOutOutput, error) {
	ret := _m.ctrl.Call(_m, "CheckIfPhoneNumberIsOptedOut", _param0)
	ret0, _ := ret[0].(*sns.CheckIfPhoneNumberIsOptedOutOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) CheckIfPhoneNumberIsOptedOut(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CheckIfPhoneNumberIsOptedOut", arg0)
}

func (_m *MockSNSAPI) ConfirmSubscriptionRequest(_param0 *sns.ConfirmSubscriptionInput) (*request.Request, *sns.ConfirmSubscriptionOutput) {
	ret := _m.ctrl.Call(_m, "ConfirmSubscriptionRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.ConfirmSubscriptionOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ConfirmSubscriptionRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ConfirmSubscriptionRequest", arg0)
}

func (_m *MockSNSAPI) ConfirmSubscription(_param0 *sns.ConfirmSubscriptionInput) (*sns.ConfirmSubscriptionOutput, error) {
	ret := _m.ctrl.Call(_m, "ConfirmSubscription", _param0)
	ret0, _ := ret[0].(*sns.ConfirmSubscriptionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ConfirmSubscription(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ConfirmSubscription", arg0)
}

func (_m *MockSNSAPI) CreatePlatformApplicationRequest(_param0 *sns.CreatePlatformApplicationInput) (*request.Request, *sns.CreatePlatformApplicationOutput) {
	ret := _m.ctrl.Call(_m, "CreatePlatformApplicationRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.CreatePlatformApplicationOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) CreatePlatformApplicationRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreatePlatformApplicationRequest", arg0)
}

func (_m *MockSNSAPI) CreatePlatformApplication(_param0 *sns.CreatePlatformApplicationInput) (*sns.CreatePlatformApplicationOutput, error) {
	ret := _m.ctrl.Call(_m, "CreatePlatformApplication", _param0)
	ret0, _ := ret[0].(*sns.CreatePlatformApplicationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) CreatePlatformApplication(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreatePlatformApplication", arg0)
}

func (_m *MockSNSAPI) CreatePlatformEndpointRequest(_param0 *sns.CreatePlatformEndpointInput) (*request.Request, *sns.CreatePlatformEndpointOutput) {
	ret := _m.ctrl.Call(_m, "CreatePlatformEndpointRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.CreatePlatformEndpointOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) CreatePlatformEndpointRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreatePlatformEndpointRequest", arg0)
}

func (_m *MockSNSAPI) CreatePlatformEndpoint(_param0 *sns.CreatePlatformEndpointInput) (*sns.CreatePlatformEndpointOutput, error) {
	ret := _m.ctrl.Call(_m, "CreatePlatformEndpoint", _param0)
	ret0, _ := ret[0].(*sns.CreatePlatformEndpointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) CreatePlatformEndpoint(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreatePlatformEndpoint", arg0)
}

func (_m *MockSNSAPI) CreateTopicRequest(_param0 *sns.CreateTopicInput) (*request.Request, *sns.CreateTopicOutput) {
	ret := _m.ctrl.Call(_m, "CreateTopicRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.CreateTopicOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) CreateTopicRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateTopicRequest", arg0)
}

func (_m *MockSNSAPI) CreateTopic(_param0 *sns.CreateTopicInput) (*sns.CreateTopicOutput, error) {
	ret := _m.ctrl.Call(_m, "CreateTopic", _param0)
	ret0, _ := ret[0].(*sns.CreateTopicOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) CreateTopic(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateTopic", arg0)
}

func (_m *MockSNSAPI) DeleteEndpointRequest(_param0 *sns.DeleteEndpointInput) (*request.Request, *sns.DeleteEndpointOutput) {
	ret := _m.ctrl.Call(_m, "DeleteEndpointRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.DeleteEndpointOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) DeleteEndpointRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteEndpointRequest", arg0)
}

func (_m *MockSNSAPI) DeleteEndpoint(_param0 *sns.DeleteEndpointInput) (*sns.DeleteEndpointOutput, error) {
	ret := _m.ctrl.Call(_m, "DeleteEndpoint", _param0)
	ret0, _ := ret[0].(*sns.DeleteEndpointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) DeleteEndpoint(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteEndpoint", arg0)
}

func (_m *MockSNSAPI) DeletePlatformApplicationRequest(_param0 *sns.DeletePlatformApplicationInput) (*request.Request, *sns.DeletePlatformApplicationOutput) {
	ret := _m.ctrl.Call(_m, "DeletePlatformApplicationRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.DeletePlatformApplicationOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) DeletePlatformApplicationRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeletePlatformApplicationRequest", arg0)
}

func (_m *MockSNSAPI) DeletePlatformApplication(_param0 *sns.DeletePlatformApplicationInput) (*sns.DeletePlatformApplicationOutput, error) {
	ret := _m.ctrl.Call(_m, "DeletePlatformApplication", _param0)
	ret0, _ := ret[0].(*sns.DeletePlatformApplicationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) DeletePlatformApplication(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeletePlatformApplication", arg0)
}

func (_m *MockSNSAPI) DeleteTopicRequest(_param0 *sns.DeleteTopicInput) (*request.Request, *sns.DeleteTopicOutput) {
	ret := _m.ctrl.Call(_m, "DeleteTopicRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.DeleteTopicOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) DeleteTopicRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteTopicRequest", arg0)
}

func (_m *MockSNSAPI) DeleteTopic(_param0 *sns.DeleteTopicInput) (*sns.DeleteTopicOutput, error) {
	ret := _m.ctrl.Call(_m, "DeleteTopic", _param0)
	ret0, _ := ret[0].(*sns.DeleteTopicOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) DeleteTopic(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteTopic", arg0)
}

func (_m *MockSNSAPI) GetEndpointAttributesRequest(_param0 *sns.GetEndpointAttributesInput) (*request.Request, *sns.GetEndpointAttributesOutput) {
	ret := _m.ctrl.Call(_m, "GetEndpointAttributesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.GetEndpointAttributesOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) GetEndpointAttributesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetEndpointAttributesRequest", arg0)
}

func (_m *MockSNSAPI) GetEndpointAttributes(_param0 *sns.GetEndpointAttributesInput) (*sns.GetEndpointAttributesOutput, error) {
	ret := _m.ctrl.Call(_m, "GetEndpointAttributes", _param0)
	ret0, _ := ret[0].(*sns.GetEndpointAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) GetEndpointAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetEndpointAttributes", arg0)
}

func (_m *MockSNSAPI) GetPlatformApplicationAttributesRequest(_param0 *sns.GetPlatformApplicationAttributesInput) (*request.Request, *sns.GetPlatformApplicationAttributesOutput) {
	ret := _m.ctrl.Call(_m, "GetPlatformApplicationAttributesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.GetPlatformApplicationAttributesOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) GetPlatformApplicationAttributesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetPlatformApplicationAttributesRequest", arg0)
}

func (_m *MockSNSAPI) GetPlatformApplicationAttributes(_param0 *sns.GetPlatformApplicationAttributesInput) (*sns.GetPlatformApplicationAttributesOutput, error) {
	ret := _m.ctrl.Call(_m, "GetPlatformApplicationAttributes", _param0)
	ret0, _ := ret[0].(*sns.GetPlatformApplicationAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) GetPlatformApplicationAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetPlatformApplicationAttributes", arg0)
}

func (_m *MockSNSAPI) GetSMSAttributesRequest(_param0 *sns.GetSMSAttributesInput) (*request.Request, *sns.GetSMSAttributesOutput) {
	ret := _m.ctrl.Call(_m, "GetSMSAttributesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.GetSMSAttributesOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) GetSMSAttributesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetSMSAttributesRequest", arg0)
}

func (_m *MockSNSAPI) GetSMSAttributes(_param0 *sns.GetSMSAttributesInput) (*sns.GetSMSAttributesOutput, error) {
	ret := _m.ctrl.Call(_m, "GetSMSAttributes", _param0)
	ret0, _ := ret[0].(*sns.GetSMSAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) GetSMSAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetSMSAttributes", arg0)
}

func (_m *MockSNSAPI) GetSubscriptionAttributesRequest(_param0 *sns.GetSubscriptionAttributesInput) (*request.Request, *sns.GetSubscriptionAttributesOutput) {
	ret := _m.ctrl.Call(_m, "GetSubscriptionAttributesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.GetSubscriptionAttributesOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) GetSubscriptionAttributesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetSubscriptionAttributesRequest", arg0)
}

func (_m *MockSNSAPI) GetSubscriptionAttributes(_param0 *sns.GetSubscriptionAttributesInput) (*sns.GetSubscriptionAttributesOutput, error) {
	ret := _m.ctrl.Call(_m, "GetSubscriptionAttributes", _param0)
	ret0, _ := ret[0].(*sns.GetSubscriptionAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) GetSubscriptionAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetSubscriptionAttributes", arg0)
}

func (_m *MockSNSAPI) GetTopicAttributesRequest(_param0 *sns.GetTopicAttributesInput) (*request.Request, *sns.GetTopicAttributesOutput) {
	ret := _m.ctrl.Call(_m, "GetTopicAttributesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.GetTopicAttributesOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) GetTopicAttributesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetTopicAttributesRequest", arg0)
}

func (_m *MockSNSAPI) GetTopicAttributes(_param0 *sns.GetTopicAttributesInput) (*sns.GetTopicAttributesOutput, error) {
	ret := _m.ctrl.Call(_m, "GetTopicAttributes", _param0)
	ret0, _ := ret[0].(*sns.GetTopicAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) GetTopicAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetTopicAttributes", arg0)
}

func (_m *MockSNSAPI) ListEndpointsByPlatformApplicationRequest(_param0 *sns.ListEndpointsByPlatformApplicationInput) (*request.Request, *sns.ListEndpointsByPlatformApplicationOutput) {
	ret := _m.ctrl.Call(_m, "ListEndpointsByPlatformApplicationRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.ListEndpointsByPlatformApplicationOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListEndpointsByPlatformApplicationRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListEndpointsByPlatformApplicationRequest", arg0)
}

func (_m *MockSNSAPI) ListEndpointsByPlatformApplication(_param0 *sns.ListEndpointsByPlatformApplicationInput) (*sns.ListEndpointsByPlatformApplicationOutput, error) {
	ret := _m.ctrl.Call(_m, "ListEndpointsByPlatformApplication", _param0)
	ret0, _ := ret[0].(*sns.ListEndpointsByPlatformApplicationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListEndpointsByPlatformApplication(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListEndpointsByPlatformApplication", arg0)
}

func (_m *MockSNSAPI) ListEndpointsByPlatformApplicationPages(_param0 *sns.ListEndpointsByPlatformApplicationInput, _param1 func(*sns.ListEndpointsByPlatformApplicationOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "ListEndpointsByPlatformApplicationPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockSNSAPIRecorder) ListEndpointsByPlatformApplicationPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListEndpointsByPlatformApplicationPages", arg0, arg1)
}

func (_m *MockSNSAPI) ListPhoneNumbersOptedOutRequest(_param0 *sns.ListPhoneNumbersOptedOutInput) (*request.Request, *sns.ListPhoneNumbersOptedOutOutput) {
	ret := _m.ctrl.Call(_m, "ListPhoneNumbersOptedOutRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.ListPhoneNumbersOptedOutOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListPhoneNumbersOptedOutRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListPhoneNumbersOptedOutRequest", arg0)
}

func (_m *MockSNSAPI) ListPhoneNumbersOptedOut(_param0 *sns.ListPhoneNumbersOptedOutInput) (*sns.ListPhoneNumbersOptedOutOutput, error) {
	ret := _m.ctrl.Call(_m, "ListPhoneNumbersOptedOut", _param0)
	ret0, _ := ret[0].(*sns.ListPhoneNumbersOptedOutOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListPhoneNumbersOptedOut(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListPhoneNumbersOptedOut", arg0)
}

func (_m *MockSNSAPI) ListPlatformApplicationsRequest(_param0 *sns.ListPlatformApplicationsInput) (*request.Request, *sns.ListPlatformApplicationsOutput) {
	ret := _m.ctrl.Call(_m, "ListPlatformApplicationsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.ListPlatformApplicationsOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListPlatformApplicationsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListPlatformApplicationsRequest", arg0)
}

func (_m *MockSNSAPI) ListPlatformApplications(_param0 *sns.ListPlatformApplicationsInput) (*sns.ListPlatformApplicationsOutput, error) {
	ret := _m.ctrl.Call(_m, "ListPlatformApplications", _param0)
	ret0, _ := ret[0].(*sns.ListPlatformApplicationsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListPlatformApplications(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListPlatformApplications", arg0)
}

func (_m *MockSNSAPI) ListPlatformApplicationsPages(_param0 *sns.ListPlatformApplicationsInput, _param1 func(*sns.ListPlatformApplicationsOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "ListPlatformApplicationsPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockSNSAPIRecorder) ListPlatformApplicationsPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListPlatformApplicationsPages", arg0, arg1)
}

func (_m *MockSNSAPI) ListSubscriptionsRequest(_param0 *sns.ListSubscriptionsInput) (*request.Request, *sns.ListSubscriptionsOutput) {
	ret := _m.ctrl.Call(_m, "ListSubscriptionsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.ListSubscriptionsOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListSubscriptionsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListSubscriptionsRequest", arg0)
}

func (_m *MockSNSAPI) ListSubscriptions(_param0 *sns.ListSubscriptionsInput) (*sns.ListSubscriptionsOutput, error) {
	ret := _m.ctrl.Call(_m, "ListSubscriptions", _param0)
	ret0, _ := ret[0].(*sns.ListSubscriptionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListSubscriptions(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListSubscriptions", arg0)
}

func (_m *MockSNSAPI) ListSubscriptionsPages(_param0 *sns.ListSubscriptionsInput, _param1 func(*sns.ListSubscriptionsOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "ListSubscriptionsPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockSNSAPIRecorder) ListSubscriptionsPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListSubscriptionsPages", arg0, arg1)
}

func (_m *MockSNSAPI) ListSubscriptionsByTopicRequest(_param0 *sns.ListSubscriptionsByTopicInput) (*request.Request, *sns.ListSubscriptionsByTopicOutput) {
	ret := _m.ctrl.Call(_m, "ListSubscriptionsByTopicRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.ListSubscriptionsByTopicOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListSubscriptionsByTopicRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListSubscriptionsByTopicRequest", arg0)
}

func (_m *MockSNSAPI) ListSubscriptionsByTopic(_param0 *sns.ListSubscriptionsByTopicInput) (*sns.ListSubscriptionsByTopicOutput, error) {
	ret := _m.ctrl.Call(_m, "ListSubscriptionsByTopic", _param0)
	ret0, _ := ret[0].(*sns.ListSubscriptionsByTopicOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListSubscriptionsByTopic(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListSubscriptionsByTopic", arg0)
}

func (_m *MockSNSAPI) ListSubscriptionsByTopicPages(_param0 *sns.ListSubscriptionsByTopicInput, _param1 func(*sns.ListSubscriptionsByTopicOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "ListSubscriptionsByTopicPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockSNSAPIRecorder) ListSubscriptionsByTopicPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListSubscriptionsByTopicPages", arg0, arg1)
}

func (_m *MockSNSAPI) ListTopicsRequest(_param0 *sns.ListTopicsInput) (*request.Request, *sns.ListTopicsOutput) {
	ret := _m.ctrl.Call(_m, "ListTopicsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.ListTopicsOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListTopicsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListTopicsRequest", arg0)
}

func (_m *MockSNSAPI) ListTopics(_param0 *sns.ListTopicsInput) (*sns.ListTopicsOutput, error) {
	ret := _m.ctrl.Call(_m, "ListTopics", _param0)
	ret0, _ := ret[0].(*sns.ListTopicsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) ListTopics(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListTopics", arg0)
}

func (_m *MockSNSAPI) ListTopicsPages(_param0 *sns.ListTopicsInput, _param1 func(*sns.ListTopicsOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "ListTopicsPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockSNSAPIRecorder) ListTopicsPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListTopicsPages", arg0, arg1)
}

func (_m *MockSNSAPI) OptInPhoneNumberRequest(_param0 *sns.OptInPhoneNumberInput) (*request.Request, *sns.OptInPhoneNumberOutput) {
	ret := _m.ctrl.Call(_m, "OptInPhoneNumberRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.OptInPhoneNumberOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) OptInPhoneNumberRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OptInPhoneNumberRequest", arg0)
}

func (_m *MockSNSAPI) OptInPhoneNumber(_param0 *sns.OptInPhoneNumberInput) (*sns.OptInPhoneNumberOutput, error) {
	ret := _m.ctrl.Call(_m, "OptInPhoneNumber", _param0)
	ret0, _ := ret[0].(*sns.OptInPhoneNumberOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) OptInPhoneNumber(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OptInPhoneNumber", arg0)
}

func (_m *MockSNSAPI) PublishRequest(_param0 *sns.PublishInput) (*request.Request, *sns.PublishOutput) {
	ret := _m.ctrl.Call(_m, "PublishRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.PublishOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) PublishRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PublishRequest", arg0)
}

func (_m *MockSNSAPI) Publish(_param0 *sns.PublishInput) (*sns.PublishOutput, error) {
	ret := _m.ctrl.Call(_m, "Publish", _param0)
	ret0, _ := ret[0].(*sns.PublishOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) Publish(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Publish", arg0)
}

func (_m *MockSNSAPI) RemovePermissionRequest(_param0 *sns.RemovePermissionInput) (*request.Request, *sns.RemovePermissionOutput) {
	ret := _m.ctrl.Call(_m, "RemovePermissionRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.RemovePermissionOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) RemovePermissionRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RemovePermissionRequest", arg0)
}

func (_m *MockSNSAPI) RemovePermission(_param0 *sns.RemovePermissionInput) (*sns.RemovePermissionOutput, error) {
	ret := _m.ctrl.Call(_m, "RemovePermission", _param0)
	ret0, _ := ret[0].(*sns.RemovePermissionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) RemovePermission(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RemovePermission", arg0)
}

func (_m *MockSNSAPI) SetEndpointAttributesRequest(_param0 *sns.SetEndpointAttributesInput) (*request.Request, *sns.SetEndpointAttributesOutput) {
	ret := _m.ctrl.Call(_m, "SetEndpointAttributesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.SetEndpointAttributesOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SetEndpointAttributesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetEndpointAttributesRequest", arg0)
}

func (_m *MockSNSAPI) SetEndpointAttributes(_param0 *sns.SetEndpointAttributesInput) (*sns.SetEndpointAttributesOutput, error) {
	ret := _m.ctrl.Call(_m, "SetEndpointAttributes", _param0)
	ret0, _ := ret[0].(*sns.SetEndpointAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SetEndpointAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetEndpointAttributes", arg0)
}

func (_m *MockSNSAPI) SetPlatformApplicationAttributesRequest(_param0 *sns.SetPlatformApplicationAttributesInput) (*request.Request, *sns.SetPlatformApplicationAttributesOutput) {
	ret := _m.ctrl.Call(_m, "SetPlatformApplicationAttributesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.SetPlatformApplicationAttributesOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SetPlatformApplicationAttributesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetPlatformApplicationAttributesRequest", arg0)
}

func (_m *MockSNSAPI) SetPlatformApplicationAttributes(_param0 *sns.SetPlatformApplicationAttributesInput) (*sns.SetPlatformApplicationAttributesOutput, error) {
	ret := _m.ctrl.Call(_m, "SetPlatformApplicationAttributes", _param0)
	ret0, _ := ret[0].(*sns.SetPlatformApplicationAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SetPlatformApplicationAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetPlatformApplicationAttributes", arg0)
}

func (_m *MockSNSAPI) SetSMSAttributesRequest(_param0 *sns.SetSMSAttributesInput) (*request.Request, *sns.SetSMSAttributesOutput) {
	ret := _m.ctrl.Call(_m, "SetSMSAttributesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.SetSMSAttributesOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SetSMSAttributesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetSMSAttributesRequest", arg0)
}

func (_m *MockSNSAPI) SetSMSAttributes(_param0 *sns.SetSMSAttributesInput) (*sns.SetSMSAttributesOutput, error) {
	ret := _m.ctrl.Call(_m, "SetSMSAttributes", _param0)
	ret0, _ := ret[0].(*sns.SetSMSAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SetSMSAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetSMSAttributes", arg0)
}

func (_m *MockSNSAPI) SetSubscriptionAttributesRequest(_param0 *sns.SetSubscriptionAttributesInput) (*request.Request, *sns.SetSubscriptionAttributesOutput) {
	ret := _m.ctrl.Call(_m, "SetSubscriptionAttributesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.SetSubscriptionAttributesOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SetSubscriptionAttributesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetSubscriptionAttributesRequest", arg0)
}

func (_m *MockSNSAPI) SetSubscriptionAttributes(_param0 *sns.SetSubscriptionAttributesInput) (*sns.SetSubscriptionAttributesOutput, error) {
	ret := _m.ctrl.Call(_m, "SetSubscriptionAttributes", _param0)
	ret0, _ := ret[0].(*sns.SetSubscriptionAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SetSubscriptionAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetSubscriptionAttributes", arg0)
}

func (_m *MockSNSAPI) SetTopicAttributesRequest(_param0 *sns.SetTopicAttributesInput) (*request.Request, *sns.SetTopicAttributesOutput) {
	ret := _m.ctrl.Call(_m, "SetTopicAttributesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.SetTopicAttributesOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SetTopicAttributesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetTopicAttributesRequest", arg0)
}

func (_m *MockSNSAPI) SetTopicAttributes(_param0 *sns.SetTopicAttributesInput) (*sns.SetTopicAttributesOutput, error) {
	ret := _m.ctrl.Call(_m, "SetTopicAttributes", _param0)
	ret0, _ := ret[0].(*sns.SetTopicAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SetTopicAttributes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetTopicAttributes", arg0)
}

func (_m *MockSNSAPI) SubscribeRequest(_param0 *sns.SubscribeInput) (*request.Request, *sns.SubscribeOutput) {
	ret := _m.ctrl.Call(_m, "SubscribeRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.SubscribeOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) SubscribeRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SubscribeRequest", arg0)
}

func (_m *MockSNSAPI) Subscribe(_param0 *sns.SubscribeInput) (*sns.SubscribeOutput, error) {
	ret := _m.ctrl.Call(_m, "Subscribe", _param0)
	ret0, _ := ret[0].(*sns.SubscribeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) Subscribe(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Subscribe", arg0)
}

func (_m *MockSNSAPI) UnsubscribeRequest(_param0 *sns.UnsubscribeInput) (*request.Request, *sns.UnsubscribeOutput) {
	ret := _m.ctrl.Call(_m, "UnsubscribeRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*sns.UnsubscribeOutput)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) UnsubscribeRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UnsubscribeRequest", arg0)
}

func (_m *MockSNSAPI) Unsubscribe(_param0 *sns.UnsubscribeInput) (*sns.UnsubscribeOutput, error) {
	ret := _m.ctrl.Call(_m, "Unsubscribe", _param0)
	ret0, _ := ret[0].(*sns.UnsubscribeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockSNSAPIRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Unsubscribe", arg0)
}
